JOB_ROUTER_ROUTE_NAMES = Kubernetes

JOB_ROUTER_ROUTE_Kubernetes @=jre
  Requirements = True
  TargetUniverse = 9

  set_JobBackend = "k8s"
  set_K8sImage = ifThenElse(isUndefined(K8sImage), "alpine:3.20", K8sImage)
@jre